// Beşeri Coğrafya: Tarım, Hayvancılık, Maden, Sanayi, Ulaşım, Turizm, Kır Yerleşme, Şehirler
const DATA_ECONOMY = {
  tarim: {
    label: "Tarım Ürünleri", icon: "🌾", color: "#f39c12",
    items: [
      { id:"tr1", name:"Fındık", lat:40.91, lng:38.39, provinces:["Ordu","Giresun","Trabzon","Sakarya","Düzce"], description:"Dünya 1. üretici. Karadeniz kıyı şeridi.", hint:"Karadeniz'in en önemli tarım ürünü" },
      { id:"tr2", name:"Çay", lat:41.02, lng:40.52, provinces:["Rize","Artvin","Trabzon"], description:"Doğu Karadeniz. Yıllık yağış fazla.", hint:"Doğu Karadeniz'e özgü ürün" },
      { id:"tr3", name:"Pamuk", lat:37.00, lng:35.32, provinces:["Adana","Şanlıurfa","Aydın","Antalya","Hatay","İzmir"], description:"Çukurova, GAP, Ege. Tekstil hammaddesi.", hint:"Çukurova ve Ege'nin beyaz altını" },
      { id:"tr4", name:"Zeytin", lat:39.60, lng:27.00, provinces:["Aydın","Muğla","Balıkesir","İzmir","Bursa","Hatay"], description:"Ege-Akdeniz kıyıları. Zeytinyağı.", hint:"Ege kıyılarının sembol ağacı" },
      { id:"tr5", name:"İncir", lat:37.85, lng:27.84, provinces:["Aydın"], description:"Dünya 1. üretici. Büyük Menderes Ovası.", hint:"Aydın'ın dünya liderliğindeki meyve" },
      { id:"tr6", name:"Kayısı", lat:38.36, lng:38.31, provinces:["Malatya"], description:"Dünya 1. üretici.", hint:"Malatya'nın dünyaca ünlü meyvesi" },
      { id:"tr7", name:"Üzüm (Kuru)", lat:38.62, lng:27.43, provinces:["Manisa"], description:"Manisa-Alaşehir üzümü. Sultani çekirdeksiz.", hint:"Manisa'nın ünlü ürünü" },
      { id:"tr8", name:"Elma", lat:37.76, lng:30.56, provinces:["Isparta","Niğde","Karaman","Denizli"], description:"Göller Yöresi en çok üretir.", hint:"Isparta'nın en çok ürettiği meyve" },
      { id:"tr9", name:"Turunçgil (Narenciye)", lat:36.81, lng:34.64, provinces:["Mersin","Adana","Antalya","Hatay"], description:"Akdeniz iklim kuşağı. Portakal,limon,mandalina.", hint:"Akdeniz kıyısının turunçgilleri" },
      { id:"tr10", name:"Antep Fıstığı", lat:37.07, lng:37.38, provinces:["Gaziantep","Şanlıurfa","Siirt","Adıyaman"], description:"Güneydoğu. Sıcak-kurak yaz.", hint:"Güneydoğu'nun yeşil altını" },
      { id:"tr11", name:"Şekerpancarı", lat:39.78, lng:30.52, provinces:["Konya","Eskişehir","Kayseri","Ankara","Yozgat"], description:"İç Anadolu karasal iklim. Şeker fabrikaları.", hint:"İç Anadolu'nun şeker hammaddesi" },
      { id:"tr12", name:"Buğday", lat:37.87, lng:32.48, provinces:["Konya","Ankara","Diyarbakır","Şanlıurfa"], description:"En çok ekilen tarla bitkisi. İç Anadolu+GAP.", hint:"İç Anadolu'nun temel tahılı" },
      { id:"tr13", name:"Ayçiçeği", lat:41.00, lng:27.52, provinces:["Tekirdağ","Edirne","Kırklareli"], description:"Trakya. Yağ sanayisi hammaddesi.", hint:"Trakya'nın sarı çiçekli ürünü" },
      { id:"tr14", name:"Gül", lat:37.76, lng:30.56, provinces:["Isparta","Burdur"], description:"Gül yağı. Isparta dünya liderlerinden.", hint:"Güller diyarının ürünü" },
      { id:"tr15", name:"Haşhaş", lat:38.75, lng:30.56, provinces:["Afyonkarahisar","Burdur","Kütahya","Denizli"], description:"İlaç sanayisi hammaddesi.", hint:"Afyon'un adını veren bitki" },
      { id:"tr16", name:"Tütün", lat:37.92, lng:40.22, provinces:["Diyarbakır","Adıyaman","Muş","Hatay","Manisa"], description:"Doğu ve Güneydoğu tütün tarımı.", hint:"Doğu'da yetiştirilen yaprak" },
      { id:"tr17", name:"Muz", lat:36.50, lng:32.00, provinces:["Mersin","Antalya"], description:"Akdeniz'in sıcak kıyılarında. Sera.", hint:"Akdeniz seracılığı meyvesi" },
      { id:"tr18", name:"Kiraz", lat:38.75, lng:30.56, provinces:["Afyonkarahisar","İzmir","Konya","Manisa"], description:"Dünya 1. üretici.", hint:"Türkiye'nin dünya 1. olduğu meyve" }
    ]
  },
  hayvancilik: {
    label: "Hayvancılık", icon: "🐄", color: "#e67e22",
    items: [
      { id:"hv1", name:"Büyükbaş (Sığır)", lat:39.90, lng:41.27, provinces:["Erzurum","Kars","Ardahan","Sivas","Konya"], description:"Doğu Anadolu çernozyom çayırlar.", hint:"Doğu Anadolu'nun hayvancılık türü" },
      { id:"hv2", name:"Küçükbaş (Koyun)", lat:37.87, lng:32.48, provinces:["Konya","Van","Ağrı","Şanlıurfa","Diyarbakır"], description:"İç/Doğu/Güneydoğu step alanları.", hint:"Step bölgelerinin hayvancılığı" },
      { id:"hv3", name:"Kıl Keçisi", lat:37.59, lng:36.94, provinces:["Kahramanmaraş","Mersin","Antalya","Adana"], description:"Toroslar ve Akdeniz dağlık bölgeleri.", hint:"Toros dağlarının keçi türü" },
      { id:"hv4", name:"Tiftik Keçisi (Ankara)", lat:39.93, lng:32.86, provinces:["Ankara","Eskişehir","Konya","Kastamonu"], description:"İç Anadolu. Ankara keçisi tiftiği.", hint:"Ankara keçisinin bölgesi" },
      { id:"hv5", name:"Arıcılık", lat:37.22, lng:28.36, provinces:["Muğla","Ordu","Adana","İçel","Aydın"], description:"Muğla çam balı dünyaca ünlü. Türkiye dünya 2.", hint:"Muğla çam balının bölgesi" },
      { id:"hv6", name:"İpekböcekçiliği", lat:40.19, lng:29.06, provinces:["Bursa","Bilecik","Sakarya","Bolu"], description:"Dut ağacı. Bursa ipekçiliği.", hint:"İpek üretiminin merkezi" },
      { id:"hv7", name:"Tavukçuluk", lat:40.73, lng:31.60, provinces:["Bolu","Sakarya","Balıkesir","Afyonkarahisar"], description:"Batı Karadeniz-Marmara geçişi.", hint:"Kanatlı hayvancılık bölgesi" },
      { id:"hv8", name:"Manda Yetiştiriciliği", lat:41.57, lng:35.90, provinces:["Samsun","Tokat","Amasya"], description:"Karadeniz bataklık alanları.", hint:"Karadeniz'deki manda bölgesi" }
    ]
  },
  madenler_enerji: {
    label: "Maden ve Enerji", icon: "⛏️", color: "#e74c3c",
    items: [
      { id:"me1", name:"Taşkömürü", lat:41.46, lng:31.80, provinces:["Zonguldak"], description:"Türkiye'nin tek taşkömürü yatağı.", hint:"Tek taşkömürü çıkan il" },
      { id:"me2", name:"Linyit (Yatağan)", lat:37.30, lng:28.15, provinces:["Muğla"], description:"Muğla-Yatağan termik santral.", hint:"Ege'nin büyük linyit yatağı" },
      { id:"me3", name:"Linyit (Soma)", lat:39.18, lng:27.60, provinces:["Manisa"], description:"Soma-Kınık linyit havzası.", hint:"Manisa'daki linyit havzası" },
      { id:"me4", name:"Linyit (Afşin-Elbistan)", lat:38.20, lng:36.95, provinces:["Kahramanmaraş"], description:"En büyük linyit yatağı. Termik santral.", hint:"En büyük linyit yatağı" },
      { id:"me5", name:"Bor Madeni", lat:39.78, lng:30.52, provinces:["Eskişehir","Kütahya","Balıkesir"], description:"Dünya bor rezervinin %73'ü Türkiye'de.", hint:"Dünya'da lider olduğumuz maden" },
      { id:"me6", name:"Krom", lat:38.68, lng:39.23, provinces:["Elazığ","Muğla","Eskişehir","Bursa","Adana"], description:"Guleman (Elazığ) en büyük yatağı.", hint:"Elazığ'daki önemli maden" },
      { id:"me7", name:"Demir", lat:39.75, lng:37.02, provinces:["Sivas","Malatya","Kayseri"], description:"Divriği (Sivas) en büyük demir yatağı.", hint:"Sivas-Divriği'deki maden" },
      { id:"me8", name:"Bakır", lat:41.18, lng:41.82, provinces:["Artvin","Kastamonu","Elazığ","Rize"], description:"Murgul (Artvin), Küre (Kastamonu).", hint:"Artvin'deki maden" },
      { id:"me9", name:"Petrol", lat:37.88, lng:41.14, provinces:["Batman","Adıyaman","Şırnak","Diyarbakır"], description:"Güneydoğu Anadolu petrol bölgesi.", hint:"Petrolün çıktığı bölge" },
      { id:"me10", name:"Boksit (Alüminyum)", lat:37.40, lng:31.70, provinces:["Konya"], description:"Seydişehir (Konya). Alüminyum fabrikası.", hint:"Konya'daki alüminyum hammaddesi" },
      { id:"me11", name:"Mermer", lat:38.75, lng:30.56, provinces:["Afyonkarahisar","Bilecik","Muğla","Burdur"], description:"Afyon ve Bilecik önemli mermer yatağı.", hint:"Afyon'un ünlü doğal taşı" },
      { id:"me12", name:"Jeotermal Enerji", lat:37.85, lng:27.84, provinces:["Aydın","Denizli","Manisa","Afyonkarahisar"], description:"Aydın Türkiye'nin jeotermal başkenti.", hint:"En çok jeotermal olan il" },
      { id:"me13", name:"RES (Rüzgâr)", lat:38.42, lng:27.13, provinces:["İzmir","Balıkesir","Çanakkale","Manisa"], description:"Ege küzey kıyıları yoğun rüzgar enerjisi.", hint:"Rüzgar enerjisinin yoğun olduğu bölge" },
      { id:"me14", name:"GES (Güneş)", lat:37.87, lng:32.48, provinces:["Konya","Şanlıurfa","Karaman","Aksaray"], description:"İç Anadolu ve Güneydoğu güneş panelleri.", hint:"Güneş enerjisinin en verimli bölgesi" },
      { id:"me15", name:"Oltu Taşı", lat:40.55, lng:41.98, provinces:["Erzurum"], description:"Oltu (Erzurum). Süs taşı.", hint:"Erzurum'un süs taşı" },
      { id:"me16", name:"Lüle Taşı", lat:39.78, lng:30.52, provinces:["Eskişehir"], description:"Eskişehir'e özgü el sanatı taşı.", hint:"Eskişehir'in el sanatı taşı" }
    ]
  },
  sanayi: {
    label: "Sanayi", icon: "🏭", color: "#95a5a6",
    items: [
      { id:"sn1", name:"Otomotiv Sanayi", lat:40.19, lng:29.06, provinces:["Bursa","Sakarya","Kocaeli","İstanbul"], description:"Marmara Bölgesi otomotiv üretim merkezi.", hint:"Marmara'daki otomotiv üssü" },
      { id:"sn2", name:"Demir-Çelik", lat:41.21, lng:32.62, provinces:["Karabük","Zonguldak","İskenderun"], description:"Karabük ilk demir-çelik. İskenderun ve Ereğli.", hint:"İlk demir-çelik fabrikasının ili" },
      { id:"sn3", name:"Tekstil Sanayi", lat:41.01, lng:28.98, provinces:["İstanbul","Bursa","Denizli","Gaziantep","Malatya"], description:"Pamuk işleme, kumaş, hazır giyim.", hint:"Tekstil ihracatı merkezi" },
      { id:"sn4", name:"Petrokimya (İzmit)", lat:40.85, lng:29.88, provinces:["Kocaeli"], description:"TÜPRAŞ rafinerisi. Petrokimya.", hint:"Türkiye'nin en büyük rafinerisi" },
      { id:"sn5", name:"Petrokimya (Batman)", lat:37.88, lng:41.14, provinces:["Batman"], description:"Güneydoğu petrol rafinerisi.", hint:"Güneydoğu'daki rafineri" },
      { id:"sn6", name:"Şeker Fabrikaları", lat:39.78, lng:30.52, provinces:["Eskişehir","Konya","Kayseri","Ankara","Yozgat"], description:"Şekerpancarı işleme. İlk: Uşak-Alpullu.", hint:"İlk şeker fabrikası bölgesi" },
      { id:"sn7", name:"Çimento Sanayi", lat:41.01, lng:28.98, provinces:["İstanbul","Ankara","İzmir","Konya","Gaziantep"], description:"Her büyük ilde var. Yapı malzemesi.", hint:"Her yerde bulunan sanayi" },
      { id:"sn8", name:"Cam Sanayi", lat:40.85, lng:29.88, provinces:["Kocaeli","Mersin","Sinop"], description:"Paşabahçe, Trakya cam.", hint:"Cam üretim merkezleri" }
    ]
  },
  ulasim: {
    label: "Ulaşım", icon: "🚂", color: "#3498db",
    items: [
      { id:"ul1", name:"İstanbul Havalimanı", lat:41.26, lng:28.74, provinces:["İstanbul"], description: "Dünyanın en büyük havalimanlarından.", hint:"Dünyanın en büyük havalimanlarından" },
      { id:"ul2", name:"Mersin Limanı", lat:36.78, lng:34.63, provinces:["Mersin"], description:"Türkiye'nin en büyük kapasiteli limanı.", hint:"En büyük kapasiteli liman" },
      { id:"ul3", name:"İzmit Limanı", lat:40.77, lng:29.95, provinces:["Kocaeli"], description:"TÜPRAŞ yakını. Sanayi limanı.", hint:"Marmara'nın sanayi limanı" },
      { id:"ul4", name:"Marmaray", lat:41.01, lng:28.98, provinces:["İstanbul"], description:"Boğaz altı demiryolu tüneli.", hint:"Boğaz'ın altından geçen tünel" },
      { id:"ul5", name:"Bakü-Tiflis-Kars Demiryolu", lat:40.60, lng:43.10, provinces:["Kars"], description:"Demir İpek Yolu. Uluslararası demiryolu.", hint:"Demir İpek Yolu'nun Türkiye çıkışı" },
      { id:"ul6", name:"İskenderun Limanı", lat:36.60, lng:36.17, provinces:["Hatay"], description:"Doğu Akdeniz limanı.", hint:"Akdeniz'in doğu limanı" }
    ]
  },
  turizm: {
    label: "Turizm", icon: "🏛️", color: "#9b59b6",
    items: [
      { id:"tu1", name:"Termal Turizm (Afyon)", lat:38.75, lng:30.56, provinces:["Afyonkarahisar","Bursa","Yalova","Denizli","Kütahya"], description:"Sıcak su kaynakları. Kaplıca.", hint:"Termal kaplıcaları ile ünlü iller" },
      { id:"tu2", name:"Kış Turizmi (Uludağ)", lat:40.07, lng:29.22, provinces:["Bursa"], description:"Marmara'nın kayak merkezi.", hint:"Marmara'nın kayak merkezi" },
      { id:"tu3", name:"Kış Turizmi (Palandöken)", lat:39.87, lng:41.32, provinces:["Erzurum"], description:"Doğu Anadolu kayak merkezi.", hint:"Doğu'nun kayak merkezi" },
      { id:"tu4", name:"Kış Turizmi (Sarıkamış)", lat:40.33, lng:42.59, provinces:["Kars"], description:"Toz kar (kristal) ile ünlü.", hint:"Toz karı ile ünlü kayak merkezi" },
      { id:"tu5", name:"Kapadokya", lat:38.69, lng:34.69, provinces:["Nevşehir","Aksaray","Niğde"], description:"Peri bacaları, balon turu. UNESCO.", hint:"Peri bacaları ve balon turu" },
      { id:"tu6", name:"Pamukkale Travertenleri", lat:37.92, lng:29.12, provinces:["Denizli"], description:"Beyaz travertenler. UNESCO.", hint:"Beyaz travertenlerin ili" },
      { id:"tu7", name:"Göbeklitepe", lat:37.22, lng:38.92, provinces:["Şanlıurfa"], description:"Dünyanın en eski tapınağı. UNESCO.", hint:"Dünyanın en eski tapınağı" },
      { id:"tu8", name:"Efes Antik Kenti", lat:37.94, lng:27.34, provinces:["İzmir"], description:"Antik Yunan/Roma kenti. UNESCO.", hint:"İzmir'deki antik kent" },
      { id:"tu9", name:"Aspendos", lat:36.94, lng:31.17, provinces:["Antalya"], description:"Roma tiyatrosu. En iyi korunmuş.", hint:"Antalya'daki Roma tiyatrosu" },
      { id:"tu10", name:"Nemrut Dağı Heykelleri", lat:37.98, lng:38.74, provinces:["Adıyaman"], description:"Kommagene Krallığı. UNESCO.", hint:"Adıyaman'daki dev heykeller" },
      { id:"tu11", name:"Sümela Manastırı", lat:40.68, lng:39.66, provinces:["Trabzon"], description:"Karadeniz kayalık manastır.", hint:"Trabzon'daki kayalık manastır" },
      { id:"tu12", name:"Safranbolu", lat:41.25, lng:32.68, provinces:["Karabük"], description:"Osmanlı evleri. UNESCO.", hint:"Osmanlı mimarisini koruyan ilçe" }
    ]
  },
  kir_yerlesmeleri: {
    label: "Kır Yerleşmeleri", icon: "🏘️", color: "#2ecc71",
    items: [
      { id:"ky1", name:"Mahalle (Karadeniz)", lat:41.00, lng:37.00, provinces:["Trabzon","Rize","Artvin","Giresun","Ordu"], description:"Karadeniz'de dağınık kır yerleşme birimi.", hint:"Karadeniz'in kır yerleşme tipi" },
      { id:"ky2", name:"Divan (Batı Karadeniz)", lat:40.73, lng:31.60, provinces:["Bolu","Düzce","Zonguldak","Kastamonu"], description:"Batı Karadeniz-İç Batı Anadolu geçişi.", hint:"Batı Karadeniz kır yerleşmesi" },
      { id:"ky3", name:"Kom (Doğu Anadolu)", lat:38.49, lng:43.41, provinces:["Van","Hakkari","Şırnak","Bitlis"], description:"Doğu'da küçük geçici/kalıcı yerleşme.", hint:"Doğu Anadolu'nun küçük yerleşmesi" },
      { id:"ky4", name:"Oba", lat:39.00, lng:33.50, provinces:["Ankara","Konya","Kayseri","Sivas"], description:"İç Anadolu yörük yerleşmesi. Geçici.", hint:"Yörüklerin geçici yerleşmesi" },
      { id:"ky5", name:"Yayla (Karadeniz)", lat:40.84, lng:41.16, provinces:["Rize","Artvin","Trabzon","Giresun"], description:"Yazın çıkılan yüksek arazi. Hayvancılık.", hint:"Karadeniz'in yüksek yaylaları" },
      { id:"ky6", name:"Yayla (Toroslar)", lat:36.90, lng:32.50, provinces:["Mersin","Antalya","Adana"], description:"Toroslar'da yazlık yerleşme.", hint:"Akdeniz'in Toros yaylaları" },
      { id:"ky7", name:"Dalyan", lat:37.00, lng:28.60, provinces:["Muğla","Aydın","İzmir","Antalya"], description:"Ege-Akdeniz kıyılarında balıkçı yerleşmesi.", hint:"Kıyıdaki balıkçı yerleşmesi" },
      { id:"ky8", name:"Çiftlik", lat:41.00, lng:27.50, provinces:["Tekirdağ","Edirne","Kırklareli","Konya","Ankara"], description:"Trakya ve İç Anadolu'da büyük tarım yerleşmesi.", hint:"Trakya'daki tarım yerleşmesi" }
    ]
  },
  sehirler: {
    label:"Şehirler (81 İl)", icon:"🏙️", color:"#9b59b6",
    items:[
      {id:"s1",name:"Adana",lat:37.00,lng:35.32,provinces:["Adana"],description:"Büyükşehir. Çukurova merkezi.",hint:"Çukurova büyükşehri"},
      {id:"s2",name:"Adıyaman",lat:37.76,lng:38.28,provinces:["Adıyaman"],description:"Nemrut Dağı. Petrol.",hint:"Nemrut'un ili"},
      {id:"s3",name:"Afyonkarahisar",lat:38.75,lng:30.56,provinces:["Afyonkarahisar"],description:"Termal, mermer, haşhaş.",hint:"Termal kaplıca ili"},
      {id:"s4",name:"Ağrı",lat:39.72,lng:43.05,provinces:["Ağrı"],description:"En yüksek dağın ili.",hint:"5137 m dağın ili"},
      {id:"s5",name:"Amasya",lat:40.65,lng:35.84,provinces:["Amasya"],description:"Şehzadeler şehri. Elma.",hint:"Şehzadeler şehri"},
      {id:"s6",name:"Ankara",lat:39.93,lng:32.86,provinces:["Ankara"],description:"Başkent. Büyükşehir. Tiftik keçisi.",hint:"Başkent"},
      {id:"s7",name:"Antalya",lat:36.90,lng:30.71,provinces:["Antalya"],description:"Büyükşehir. Turizm başkenti.",hint:"Turizm başkenti"},
      {id:"s8",name:"Artvin",lat:41.18,lng:41.82,provinces:["Artvin"],description:"Çoruh Vadisi. Bakır madeni.",hint:"Çoruh Vadisi'nin ili"},
      {id:"s9",name:"Aydın",lat:37.86,lng:27.84,provinces:["Aydın"],description:"Büyükşehir. İncir, zeytin, pamuk.",hint:"İncirin başkenti"},
      {id:"s10",name:"Balıkesir",lat:39.65,lng:27.88,provinces:["Balıkesir"],description:"Büyükşehir. İki denizli il.",hint:"İki denize kıyısı olan il"},
      {id:"s11",name:"Bilecik",lat:40.06,lng:30.02,provinces:["Bilecik"],description:"Mermer. İpekböcekçiliği.",hint:"Osmanlı kuruluş bölgesi"},
      {id:"s12",name:"Bingöl",lat:38.89,lng:40.50,provinces:["Bingöl"],description:"Bin göl. Deprem bölgesi.",hint:"Adını göllerinden alan il"},
      {id:"s13",name:"Bitlis",lat:38.40,lng:42.11,provinces:["Bitlis"],description:"Van Gölü batısı. Nemrut Krater.",hint:"Van Gölü batısı"},
      {id:"s14",name:"Bolu",lat:40.74,lng:31.61,provinces:["Bolu"],description:"Abant-Yedigöller. Aşçılık.",hint:"Abant Gölü'nün ili"},
      {id:"s15",name:"Burdur",lat:37.72,lng:30.29,provinces:["Burdur"],description:"Salda Gölü. Göller Yöresi.",hint:"Salda Gölü'nün ili"},
      {id:"s16",name:"Bursa",lat:40.19,lng:29.06,provinces:["Bursa"],description:"Büyükşehir. Osmanlı ilk başkent. Otomotiv.",hint:"Osmanlı ilk başkenti"},
      {id:"s17",name:"Çanakkale",lat:40.16,lng:26.41,provinces:["Çanakkale"],description:"Boğaz, Gelibolu, Truva.",hint:"Boğazın ve Truva'nın ili"},
      {id:"s18",name:"Çankırı",lat:40.60,lng:33.61,provinces:["Çankırı"],description:"Kaya tuzu madeni.",hint:"Kaya tuzu ili"},
      {id:"s19",name:"Çorum",lat:40.55,lng:34.96,provinces:["Çorum"],description:"Hattuşaş (Hitit başkenti). Leblebi.",hint:"Hititler'in başkenti"},
      {id:"s20",name:"Denizli",lat:37.78,lng:29.09,provinces:["Denizli"],description:"Büyükşehir. Pamukkale. Tekstil.",hint:"Pamukkale'nin ili"},
      {id:"s21",name:"Diyarbakır",lat:37.92,lng:40.22,provinces:["Diyarbakır"],description:"Büyükşehir. Surlar. Dicle kıyısı.",hint:"Surlarıyla ünlü şehir"},
      {id:"s22",name:"Edirne",lat:41.68,lng:26.56,provinces:["Edirne"],description:"Osmanlı 2. başkent. Selimiye.",hint:"Osmanlı ikinci başkenti"},
      {id:"s23",name:"Elazığ",lat:38.68,lng:39.23,provinces:["Elazığ"],description:"Keban-Hazar. Krom madeni.",hint:"Hazar Gölü'nün ili"},
      {id:"s24",name:"Erzincan",lat:39.75,lng:39.50,provinces:["Erzincan"],description:"Fırat geçer. Deprem.",hint:"Fırat boyunca uzanan il"},
      {id:"s25",name:"Erzurum",lat:39.90,lng:41.27,provinces:["Erzurum"],description:"Büyükşehir. Palandöken. Çernozyom.",hint:"Doğu'nun en büyük şehri"},
      {id:"s26",name:"Eskişehir",lat:39.78,lng:30.52,provinces:["Eskişehir"],description:"Büyükşehir. Lüle taşı, bor madeni.",hint:"Lüle taşı ve üniversite şehri"},
      {id:"s27",name:"Gaziantep",lat:37.07,lng:37.38,provinces:["Gaziantep"],description:"Büyükşehir. Mutfağı UNESCO.",hint:"Mutfak kültürü UNESCO ili"},
      {id:"s28",name:"Giresun",lat:40.91,lng:38.39,provinces:["Giresun"],description:"Fındık üretimi. Giresun Adası.",hint:"Fındığın başkenti"},
      {id:"s29",name:"Gümüşhane",lat:40.44,lng:39.51,provinces:["Gümüşhane"],description:"Karaca Mağarası.",hint:"Karaca Mağarası'nın ili"},
      {id:"s30",name:"Hakkari",lat:37.58,lng:43.74,provinces:["Hakkari"],description:"En güneydoğu. Cilo. Dağlık.",hint:"En güneydoğu ili"},
      {id:"s31",name:"Hatay",lat:36.20,lng:36.15,provinces:["Hatay"],description:"Büyükşehir. En güney. Asi Nehri.",hint:"En güneydeki büyükşehir"},
      {id:"s32",name:"Isparta",lat:37.76,lng:30.56,provinces:["Isparta"],description:"Gül, elma. Göller Yöresi.",hint:"Güller diyarı"},
      {id:"s33",name:"Mersin",lat:36.81,lng:34.64,provinces:["Mersin"],description:"Büyükşehir. En büyük liman. Muz.",hint:"Akdeniz liman büyükşehri"},
      {id:"s34",name:"İstanbul",lat:41.01,lng:28.98,provinces:["İstanbul"],description:"Büyükşehir. En kalabalık. İki kıta.",hint:"İki kıtayı birleştiren şehir"},
      {id:"s35",name:"İzmir",lat:38.42,lng:27.13,provinces:["İzmir"],description:"Büyükşehir. 3. büyük şehir. Ege'nin incisi.",hint:"Ege'nin incisi"},
      {id:"s36",name:"Kars",lat:40.60,lng:43.10,provinces:["Kars"],description:"Ani Harabeleri. Sarıkamış. Peynir.",hint:"Ani Harabeleri'nin ili"},
      {id:"s37",name:"Kastamonu",lat:41.39,lng:33.78,provinces:["Kastamonu"],description:"İlk şapka inkılabı. Küre Dağları.",hint:"Şapka inkılabının ili"},
      {id:"s38",name:"Kayseri",lat:38.73,lng:35.48,provinces:["Kayseri"],description:"Büyükşehir. Erciyes. Sanayi.",hint:"Erciyes'in gölgesindeki şehir"},
      {id:"s39",name:"Kırklareli",lat:41.73,lng:27.22,provinces:["Kırklareli"],description:"Trakya. Bulgaristan sınırı. Istranca.",hint:"Trakya kuzeyi, Istranca masifi"},
      {id:"s40",name:"Kırşehir",lat:39.14,lng:34.17,provinces:["Kırşehir"],description:"Ahilik merkezi. Kırşehir Masifi.",hint:"Ahilik'in merkezi"},
      {id:"s41",name:"Kocaeli",lat:40.85,lng:29.88,provinces:["Kocaeli"],description:"Büyükşehir. Sanayi. TÜPRAŞ.",hint:"İzmit sanayi büyükşehri"},
      {id:"s42",name:"Konya",lat:37.87,lng:32.48,provinces:["Konya"],description:"Büyükşehir. En büyük yüzölçüm. Mevlana.",hint:"En büyük yüzölçümlü il"},
      {id:"s43",name:"Kütahya",lat:39.42,lng:29.98,provinces:["Kütahya"],description:"Çini sanatı. Bor madeni.",hint:"Çinicilik merkezi"},
      {id:"s44",name:"Malatya",lat:38.36,lng:38.31,provinces:["Malatya"],description:"Büyükşehir. Kayısı başkenti.",hint:"Kayısının başkenti"},
      {id:"s45",name:"Manisa",lat:38.62,lng:27.43,provinces:["Manisa"],description:"Büyükşehir. Üzüm. Soma linyit.",hint:"Üzümün başkenti"},
      {id:"s46",name:"Kahramanmaraş",lat:37.59,lng:36.94,provinces:["Kahramanmaraş"],description:"Büyükşehir. Dondurma. Afşin-Elbistan.",hint:"Dondurma ili"},
      {id:"s47",name:"Mardin",lat:37.32,lng:40.72,provinces:["Mardin"],description:"Büyükşehir. Taş evler. Midyat.",hint:"Taş mimarisinin ili"},
      {id:"s48",name:"Muğla",lat:37.22,lng:28.36,provinces:["Muğla"],description:"Büyükşehir. Bodrum,Fethiye. Sığla ağacı.",hint:"Bodrum-Marmaris ili"},
      {id:"s49",name:"Muş",lat:38.74,lng:41.51,provinces:["Muş"],description:"Murat Nehri. Tektonik ova.",hint:"Murat Nehri ovası"},
      {id:"s50",name:"Nevşehir",lat:38.69,lng:34.69,provinces:["Nevşehir"],description:"Kapadokya. Peri bacaları.",hint:"Kapadokya'nın ili"},
      {id:"s51",name:"Niğde",lat:37.97,lng:34.68,provinces:["Niğde"],description:"Aladağlar. Elma üretimi.",hint:"Aladağlar'ın ili"},
      {id:"s52",name:"Ordu",lat:40.98,lng:37.88,provinces:["Ordu"],description:"Büyükşehir. Fındık.",hint:"Fındık büyükşehri"},
      {id:"s53",name:"Rize",lat:41.02,lng:40.52,provinces:["Rize"],description:"Çay başkenti. En çok yağış.",hint:"Çayın başkenti"},
      {id:"s54",name:"Sakarya",lat:40.69,lng:30.44,provinces:["Sakarya"],description:"Büyükşehir. Fındık, tavukçuluk.",hint:"Sakarya Nehri ili"},
      {id:"s55",name:"Samsun",lat:41.29,lng:36.33,provinces:["Samsun"],description:"Büyükşehir. 19 Mayıs. Bafra-Çarşamba.",hint:"19 Mayıs'ın başlangıcı"},
      {id:"s56",name:"Siirt",lat:37.93,lng:41.95,provinces:["Siirt"],description:"Büryan kebabı. Antep fıstığı.",hint:"Büryan'ın yurdu"},
      {id:"s57",name:"Sinop",lat:42.02,lng:35.15,provinces:["Sinop"],description:"En kuzey noktası. İnce Burun.",hint:"Türkiye'nin en kuzeyi"},
      {id:"s58",name:"Sivas",lat:39.75,lng:37.02,provinces:["Sivas"],description:"Kızılırmak kaynağı. Divriği demir.",hint:"Kızılırmak'ın doğduğu il"},
      {id:"s59",name:"Tekirdağ",lat:41.00,lng:27.52,provinces:["Tekirdağ"],description:"Büyükşehir. Ayçiçeği. Trakya.",hint:"Trakya büyükşehri"},
      {id:"s60",name:"Tokat",lat:40.32,lng:36.55,provinces:["Tokat"],description:"Yeşilırmak. Erbaa-Niksar ovası.",hint:"Yeşilırmak'ın geçtiği il"},
      {id:"s61",name:"Trabzon",lat:41.00,lng:39.72,provinces:["Trabzon"],description:"Büyükşehir. Sümela. Fındık.",hint:"Doğu Karadeniz büyükşehri"},
      {id:"s62",name:"Tunceli",lat:39.11,lng:39.54,provinces:["Tunceli"],description:"Munzur Vadisi. En az nüfus.",hint:"En az nüfuslu il"},
      {id:"s63",name:"Şanlıurfa",lat:37.16,lng:38.80,provinces:["Şanlıurfa"],description:"Büyükşehir. Göbeklitepe. GAP.",hint:"Göbeklitepe'nin ili"},
      {id:"s64",name:"Uşak",lat:38.68,lng:29.41,provinces:["Uşak"],description:"Halıcılık. İlk şeker fabrikası.",hint:"Halıcılık ve ilk şeker fabrikası"},
      {id:"s65",name:"Van",lat:38.49,lng:43.41,provinces:["Van"],description:"Büyükşehir. Van Gölü. Van kedisi.",hint:"Gölü ve kedisiyle ünlü il"},
      {id:"s66",name:"Yozgat",lat:39.82,lng:34.81,provinces:["Yozgat"],description:"Bozok Platosu. Çamlık.",hint:"Bozok Platosu'nun ili"},
      {id:"s67",name:"Zonguldak",lat:41.46,lng:31.80,provinces:["Zonguldak"],description:"Taşkömürü. Ereğli demir-çelik.",hint:"Taşkömürünün ili"},
      {id:"s68",name:"Aksaray",lat:38.37,lng:34.04,provinces:["Aksaray"],description:"Ihlara Vadisi. Hasan Dağı.",hint:"Ihlara Vadisi'nin ili"},
      {id:"s69",name:"Bayburt",lat:40.26,lng:40.22,provinces:["Bayburt"],description:"Çoruh kaynağı. En küçük nüfus.",hint:"En küçük illerden"},
      {id:"s70",name:"Karaman",lat:37.18,lng:33.23,provinces:["Karaman"],description:"Karamanoğulları. Elma üretimi.",hint:"Türkçe resmi dil ilan yeri"},
      {id:"s71",name:"Kırıkkale",lat:39.85,lng:33.52,provinces:["Kırıkkale"],description:"Silah sanayi. Ankara yakını.",hint:"Silah sanayisi ili"},
      {id:"s72",name:"Batman",lat:37.88,lng:41.14,provinces:["Batman"],description:"Petrol rafinerisi.",hint:"Petrol rafinerisi ili"},
      {id:"s73",name:"Şırnak",lat:37.42,lng:42.49,provinces:["Şırnak"],description:"Cudi Dağı. Petrol.",hint:"Cudi Dağı'nın ili"},
      {id:"s74",name:"Bartın",lat:41.63,lng:32.34,provinces:["Bartın"],description:"Küre Dağları. Batı Karadeniz.",hint:"Batı Karadeniz kıyı ili"},
      {id:"s75",name:"Ardahan",lat:41.11,lng:42.70,provinces:["Ardahan"],description:"Çıldır Gölü. Kars Platosu.",hint:"Çıldır Gölü'nün ili"},
      {id:"s76",name:"Iğdır",lat:39.92,lng:44.05,provinces:["Iğdır"],description:"Ağrı Dağı güneyinde. Mikro iklim.",hint:"En doğudaki ova şehri"},
      {id:"s77",name:"Yalova",lat:40.65,lng:29.27,provinces:["Yalova"],description:"Termal kaplıca. En küçük yüzölçüm.",hint:"En küçük yüzölçümlü il"},
      {id:"s78",name:"Karabük",lat:41.21,lng:32.62,provinces:["Karabük"],description:"Safranbolu. İlk demir-çelik.",hint:"Safranbolu'nun ili"},
      {id:"s79",name:"Kilis",lat:36.72,lng:37.12,provinces:["Kilis"],description:"Suriye sınırı. Zeytin.",hint:"Suriye sınırındaki il"},
      {id:"s80",name:"Osmaniye",lat:37.07,lng:36.25,provinces:["Osmaniye"],description:"Amanos Dağları. Ceyhan geçer.",hint:"Amanos eteklerindeki il"},
      {id:"s81",name:"Düzce",lat:40.84,lng:31.16,provinces:["Düzce"],description:"81. il. Fındık üretimi.",hint:"En son kurulan il"}
    ]
  }
};
