name: Android App Build (TWA)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build Android App Bundle (.aab)
        run: |
          # --yes parametresi tüm soruları "Varsayılan" olarak geçer
          # --skipConfig ise JDK kurulumu gibi soruları pas geçmemizi sağlar
          bubblewrap init --manifest=https://cografya25.netlify.app/manifest.json --allowlist=https://cografya25.netlify.app/ --yes
          bubblewrap build --signingKeyPath=./my-release-key.keystore --signingKeyAlias=${{ secrets.KEY_ALIAS }} --yes
        env:
          BUBBLEWRAP_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          BUBBLEWRAP_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v5
        with:
          name: release-aab
          path: ./*.aab
