name: Android App Build (TWA)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build Android App Bundle (.aab)
        run: |
          bubblewrap init --manifest=https://cografya25.netlify.app/manifest.json --allowlist=https://cografya25.netlify.app/
          bubblewrap build --signingKeyPath=./my-release-key.keystore --signingKeyAlias=${{ secrets.KEY_ALIAS }}
        env:
          BUBBLEWRAP_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          BUBBLEWRAP_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-aab
          path: ./*.aab
